<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>Yangfulai</Authors>
    <Description>DataPieCore</Description>
    <Copyright>Yangfulai</Copyright>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DataPieCore.RegressionTests" />
    <PackageReference Include="EPPlus" Version="8.7.0" />
    <PackageReference Include="ExcelDataReader" Version="3.9.0" />
    <PackageReference Include="MiniExcel" Version="1.46.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

</Project>
